version: '3'
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - '8080:8080'
      - '9000:9000'
      - "2222:22"
      - "35729:35729"
      - "9876:9876"
    volumes:
      - '.:/opt/app-root/src'
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
      APP_ENV: development
      APP_KEY: 'base64:9Dxc6fGW2BBuu/z0PLs5z+14vmmhfO1wB3JRGZXjtTg='
      APP_DEBUG: 'true'
      XDEBUG_CONFIG: remote_host=10.254.254.254
  db:
    image: 'mysql:5.7'
    volumes:
      - './tmp/db:/var/lib/postgresql/data'
    environment:
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_DATABASE: laravel
  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
